### PR TITLE
Add eWW project kickoff post

### PR DESCRIPTION
**Pull request by acka47**
Resolves https://github.com/skohub-io/skohub-vocabs/issues/190

### CODE REVIEW

**Comment by acka47** [comment]
@axenzen Let me know whether this is ok. Here is a screenshot of what the post would look like on the blog so that you don't have to set it up yourself locally:

grafik

**Comment by acka47** [comment]
I added the issue number with [a9648b5](https://github.com/skohub-io/skohub-blog/pull/10/commits/a9648b527ab84dcf45abd4d67d2c60d391549132) that is missing in the screenshot

**Comment by axenzen** [comment]
Looking good, Adrian, thanks. I would omit the word "yesterday" in the first sentence, or put it like this: In a kick-off workshop yesterday, the SkoHub team at hbz..."

**Comment by acka47** [comment]
Thanks, I updated the publication date to today (didn't expect us to be that quick) and will no merge/publish.

**Pull request merged**
