### PR TITLE
Add Blog Post about improvement in SkoHub Pages #34

### PR DESCRIPTION
**Pull request by sroertgen**
I also changed the repo name of `skohub-docker-vocabs` to `skohub-pages` (https://github.com/skohub-io/skohub-pages).

### CODE REVIEW

**Review by acka47 — CHANGES_REQUESTED** [review]
I think we should start the post by describing the workflow with some screenshots and should also add an outlook on making this less dependant on GitHub infrastructure. I have started writing this but haven't finished.

**Comment by sroertgen** [comment]
I added some screenshots and adjusted a little bit.

**Comment by acka47** [comment]
I have made some more edits. I suggest to read this again tomorrow, fix the last errors and then publish.

**Review by acka47 — APPROVED** [review]
I am very happy with this now. Except for the red in the screenshots maybe, where the SkoHub pink (R230 G0 B125 #e6007d) would look better. If you like, you can adjust it, @sroertgen , but I am also fine with it as is.

**Pull request merged**
